{{- if .Values.sentryDSN }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-holmes-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: holmes
type: Opaque
stringData:
  sentry-dsn: {{ .Values.sentryDSN | quote }}
{{- end }}
